# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
#use_frameworks!

target 'EventHub' do

pod "AFNetworking"
pod "BDBOAuth1Manager"
pod "MBProgressHUD"
#pod "TNImageSliderViewController"

end

target 'EventHubTests' do

end

