# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
#use_frameworks!

target 'EventHub' do

pod "AFNetworking"
pod "BDBOAuth1Manager"
#pod "TNImageSliderViewController"
pod "DXCustomCallout-ObjC"
pod 'MBProgressHUD', '~> 0.9.1'
end

target 'EventHubTests' do

end

