# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, "8.0"
target 'EventHub' do

pod "AFNetworking"
pod "BDBOAuth1Manager"
pod "MBProgressHUD"

end

target 'EventHubTests' do

end

